---
- name: Create container
  community.general.lxc_container:
    name: "{{ item.name }}"
    state: started
    template: "{{ item.template }}"
    template_options: "{{ item.opts }}"
    backing_store: dir #loop
    config:
      - lxc.start.auto=1
  loop: "{{ containers }}"

- name: Remove absent containers
  community.general.lxc_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ absent_containers }}"