---
- name: Create container
  community.general.lxc_container:
    name: "{{ item.name }}"
    state: started
    template: "{{ item.template }}"
    template_options: "{{ item.opts }}"
    backing_store: dir #loop
    container_config:
      - "lxc.start.auto = {{ item.start_auto | default('0') }}"
      - "lxc.net.0.type = {{ item.lxc_net_type | default(lxc_default.lxc_net_type) }}"
      - "lxc.net.0.link = {{ item.lxc_net_link | default(lxc_default.lxc_net_link) }}"
      - "lxc.net.0.flags = up"
  loop: "{{ containers }}"

- name: Remove absent containers
  community.general.lxc_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ absent_containers }}"